<<<<<<< HEAD
spring.application.name=backend
# DB ?? ?? (??? ??)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=GGORI
spring.datasource.password=1234

# JPA/Hibernate ??
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8111
=======
spring.application.name=middle
server.port=8111

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=GGORI
spring.datasource.password=1234

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.security=DEBUG
>>>>>>> d51c9638d47420810ad33e5d6459fe0db79d2b57
