spring.application.name=backend
server.port=8111

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ggori_salang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=root
spring.datasource.password=1234

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.security=DEBUG
